### ISSUE TITLE
Metrics monotonically increase when batch-processing

### ISSUE THREAD

**Issue by birchera** [marcojob/sbf_viewer#4]
The counters do not seem to be reset before processing the next sbf file.

![image](https://user-images.githubusercontent.com/2298059/99228673-eee02780-27ba-11eb-9ebd-2e9fb96f25e1.png)

FYI @marcojob

**Comment by birchera** [comment]
Also the other values do seem to have some repetitions of the same values

[ppk_quality_output.txt](https://github.com/marcojob/sbf_viewer/files/5545007/ppk_quality_output.txt)

**Comment by marcojob** [comment]
Very true, the counters reset is not done properly. @birchera can you try with PR #5 again?
